"""autogenerate add column

Revision ID: b9216e774065
Revises: c5657c5977b4
Create Date: 2025-09-16 10:26:47.913378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9216e774065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'books', type_='foreignkey')
    #op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
